---
name: gym
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  bitsdojo_window: ^0.1.1+1
  bloc: ^7.1.0
  conditional_builder_null_safety: ^0.0.4
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  font_awesome_flutter: ^9.1.0
  slide_digital_clock: ^1.0.2
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/products/
    - assets/public/
    - assets/trainers/
    - assets/members/
